============================= test session starts ==============================
platform darwin -- Python 3.12.7, pytest-7.4.4, pluggy-1.0.0 -- /Users/patransil/anaconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/patransil/dev/agentic_programming/framework/blackjack_game/deliverables
plugins: anyio-4.9.0
collecting ... collected 0 items / 2 errors

==================================== ERRORS ====================================
______________________ ERROR collecting test/test_api.py _______________________
ImportError while importing test module '/Users/patransil/dev/agentic_programming/framework/blackjack_game/deliverables/test/test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../anaconda3/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_api.py:9: in <module>
    from fastapi.testclient import TestClient
E   ModuleNotFoundError: No module named 'fastapi'
__________________ ERROR collecting test/test_game_engine.py ___________________
test/test_game_engine.py:13: in <module>
    from game_engine import (
src/game_engine.py:19: in <module>
    class Rank(Enum):
../../../../../anaconda3/lib/python3.12/enum.py:606: in __new__
    raise exc.with_traceback(tb)
../../../../../anaconda3/lib/python3.12/enum.py:596: in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
../../../../../anaconda3/lib/python3.12/enum.py:287: in __set_name__
    enum_member.__init__(*args)
src/game_engine.py:35: in __init__
    self.value = value
../../../../../anaconda3/lib/python3.12/enum.py:230: in __set__
    raise AttributeError(
E   AttributeError: <enum 'Enum'> cannot set attribute 'value'
=========================== short test summary info ============================
ERROR test/test_api.py
ERROR test/test_game_engine.py - AttributeError: <enum 'Enum'> cannot set att...
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.34s ===============================
